### ISSUE TITLE
cool!

### ISSUE THREAD

**Issue by aquynh** [kevinkoo001/ropf#1]
this looks nice, but where to get the paper behind it?

keep it up, cheers!

**Comment by kevinkoo001** [comment]
Here are the links for the paper and the article:

http://goo.gl/YijOqh
http://dandylife.net/blog/archives/606

Thanks!

On Tue, May 31, 2016 at 1:26 PM, Nguyen Anh Quynh notifications@github.com
wrote:

> this looks nice, but where to get the paper behind it?
> 
> keep it up, cheers!
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/kevinkoo001/ropf/issues/1, or mute the thread
> https://github.com/notifications/unsubscribe/AD64j63fxpOp1qpLAfRJrUaUHroU0Y7nks5qHG8qgaJpZM4Iqw__
> .

## 

Best Regards,
HyungJoon Koo
